name: Build and Test Flask Application

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest  # Install pytest

      - name: Run tests with pytest
        run: |
          source venv/bin/activate
          pytest testapp.py
